### ISSUE TITLE
Use dedicated repo to share label configuration across an org

### ISSUE THREAD

**Issue by tlvenn** [facelessuser/label-bot#55]
Storing label definition in a config file on the repo itself is pretty great however there are many instances where like 70% of the labels are strictly the same across repos of a given org by design to enforce convention over common ones (Severity, Priority, Kind, etc..).

It would be great if there was a way to have a dedicated repo to host the master definition which could be complemented at the repo level for specific project need.

**Comment by facelessuser** [comment]
I myself do use many of the same labels across repos. Mainly the source specific labels are the ones that differ...for me at least. It would be nice to have that stuff change in one place, and be carried across multiple repositories when they next sync. You could theoretically even just store them in a gist, but a repo could certainly work too.

It'd be cheaper (less API calls) just to send the base config up with the app. Or just load it once during initialization. You'd have to restart/re-deploy to pick up the latest though...I guess you could expose a command for that as well.

I'm interested in exploring ideas. This is kind of a big experiment right now. I'm finding it useful, but still figuring out the best direction.

@gir-bot add feature, needs-decision
@gir-bot remove triage

**Comment by facelessuser** [comment]
I think I'm going to go ahead and add this.

@gir-bot lgtm

**Comment by facelessuser** [comment]
Change is detailed here: https://github.com/facelessuser/label-bot#using-a-master-configuration-template

**Comment by facelessuser** [comment]
I will most likely change this to look in the local repo config to see where to find the master config. This will allow more flexibility. I'll do this tomorrow.

**Comment by facelessuser** [comment]
Change has been made
